In [23]:
import pandas as pd
import numpy as np
import random
import datetime

In [24]:
data = pd.read_excel('data.xlsx')
data

x1       x2       x3       x4       x5       x6       x7       x8  \
0   1.56186 -2.54905 -1.98638 -0.30684 -1.00062  3.52667  2.62601 -0.30951   
1   3.89045 -0.02852  2.20650  1.20511  0.12892  1.16363  1.41855 -1.30547   
2  -1.85626 -1.38071 -0.07550 -2.90992 -2.75206 -0.23195 -1.10457 -1.11643   
3  -1.58778 -2.07548  0.00738 -4.24154  0.91851 -5.61822  0.97835  0.06143   
4   2.15052  5.26269 -1.26788 -2.68478 -1.15078 -0.36360  0.74234  1.31526   
..      ...      ...      ...      ...      ...      ...      ...      ...   
95 -3.08999 -3.59724  5.58267 -0.73572  5.16949  3.41667 -0.97299 -0.67884   
96 -0.17985  1.50163  0.66528  1.89992  0.79647 -1.60727  0.31752 -0.06467   
97 -3.81450  0.89167 -2.15984 -3.80682 -4.75878 -0.78957 -0.28329  0.45259   
98 -2.11276 -1.91391 -0.63889 -3.53088 -2.24357 -1.22243  0.65278  2.75600   
99 -2.50787 -1.02966  0.52740  3.15535 -3.28735  1.44250  1.93997 -0.31516   

         x9      x10  y  
0   1.32496 -2.26376 -1  
1  -2.31854 -1.40395 -1  
2  -2.35446 -1.43411  1  
3   4.33760 -1.50129  1  
4  -2.77029 -0.14857  1  
..      ...      ... ..  
95  0.98183 -0.39283 -1  
96 -0.51961  3.71141 -1  
97 -1.57172  0.15997  1  
98 -3.45234 -1.29036  1  
99  1.14198  0.64107 -1  

[100 rows x 11 columns]

In [25]:
# add x0 = 1 to every xn
x0_list = [1] * len(data)
data = pd.concat([pd.Series(x0_list), data], axis=1)
data = data.rename(columns={0: 'x0'})
data

x0       x1       x2       x3       x4       x5       x6       x7  \
0    1  1.56186 -2.54905 -1.98638 -0.30684 -1.00062  3.52667  2.62601   
1    1  3.89045 -0.02852  2.20650  1.20511  0.12892  1.16363  1.41855   
2    1 -1.85626 -1.38071 -0.07550 -2.90992 -2.75206 -0.23195 -1.10457   
3    1 -1.58778 -2.07548  0.00738 -4.24154  0.91851 -5.61822  0.97835   
4    1  2.15052  5.26269 -1.26788 -2.68478 -1.15078 -0.36360  0.74234   
..  ..      ...      ...      ...      ...      ...      ...      ...   
95   1 -3.08999 -3.59724  5.58267 -0.73572  5.16949  3.41667 -0.97299   
96   1 -0.17985  1.50163  0.66528  1.89992  0.79647 -1.60727  0.31752   
97   1 -3.81450  0.89167 -2.15984 -3.80682 -4.75878 -0.78957 -0.28329   
98   1 -2.11276 -1.91391 -0.63889 -3.53088 -2.24357 -1.22243  0.65278   
99   1 -2.50787 -1.02966  0.52740  3.15535 -3.28735  1.44250  1.93997   

         x8       x9      x10  y  
0  -0.30951  1.32496 -2.26376 -1  
1  -1.30547 -2.31854 -1.40395 -1  
2  -1.11643 -2.35446 -1.43411  1  
3   0.06143  4.33760 -1.50129  1  
4   1.31526 -2.77029 -0.14857  1  
..      ...      ...      ... ..  
95 -0.67884  0.98183 -0.39283 -1  
96 -0.06467 -0.51961  3.71141 -1  
97  0.45259 -1.57172  0.15997  1  
98  2.75600 -3.45234 -1.29036  1  
99 -0.31516  1.14198  0.64107 -1  

[100 rows x 12 columns]

In [26]:
data_copy = data.copy()

In [27]:
y = data_copy['y']
data_copy = data_copy.drop('y', axis=1)

In [28]:
def sign(z):
    if z > 0:
        return 1
    else:
        return -1

In [29]:
# trial sample
np.array(data_copy.sample(n=1))

array([[ 1.     , -0.28947,  0.68382,  0.28025,  3.2333 ,  1.19489,
         0.73396, -0.8776 , -1.33655,  1.14321,  2.5369 ]])

In [30]:
# trial w0
w0 = np.array([0] * 11)
w0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
# trial np.array()
np.array(data_copy.loc[1, :])

array([ 1.     ,  3.89045, -0.02852,  2.2065 ,  1.20511,  0.12892,
        1.16363,  1.41855, -1.30547, -2.31854, -1.40395])

In [32]:
# trial dot
type(np.dot(w0, np.array(data_copy.loc[1, :])))

numpy.float64

In [33]:
def pla(data, y):
    w = np.array([0.] * 11)
    N = len(data)
    counter = 1
    while counter <= (5 * N):
        rd_index = random.randint(0, N - 1)
        rd_y = y[rd_index]
        rd_x = np.array(data.iloc[rd_index, :])
        
        # check ans
        if sign(np.dot(w, rd_x)) != rd_y:  # mistake
            counter = 1
            w += rd_y * rd_x
        else:
            counter += 1

    return w

In [34]:
a = pla(data_copy, y)
print(a)
np.linalg.norm(a) ** 2

[-11.       -2.12089   3.6477    1.7858  -14.14534 -11.72611  -6.65725
  -6.05199  -2.9818    2.92288  -8.27231]


646.3963027629002

In [146]:
# Q13
totalsqrnorm = 0
print('start:', datetime.datetime.now())
for i in range(1000):
    seed = i
    if (seed % 100) == 0:
        print(seed)

    wpla = pla(data=data_copy, y=y)
    totalsqrnorm += np.linalg.norm(wpla) ** 2
print('end:', datetime.datetime.now())
avgsqrnorm = totalsqrnorm / 1000
print(avgsqrnorm)

start: 2021-10-16 21:05:09.236842
0
100
200
300
400
500
600
700
800
900
end: 2021-10-16 21:07:42.782872
393.15928262241437


In [35]:
# Q14 Scaling up x by 2
temp = np.matrix(data_copy)
temp *= 2
temp

matrix([[ 2.     ,  3.12372, -5.0981 , ..., -0.61902,  2.64992, -4.52752],
        [ 2.     ,  7.7809 , -0.05704, ..., -2.61094, -4.63708, -2.8079 ],
        [ 2.     , -3.71252, -2.76142, ..., -2.23286, -4.70892, -2.86822],
        ...,
        [ 2.     , -7.629  ,  1.78334, ...,  0.90518, -3.14344,  0.31994],
        [ 2.     , -4.22552, -3.82782, ...,  5.512  , -6.90468, -2.58072],
        [ 2.     , -5.01574, -2.05932, ..., -0.63032,  2.28396,  1.28214]])

In [36]:
x_cols = list(data_copy.columns)
temp = pd.DataFrame(temp, columns=x_cols)
temp.head(5)

x0       x1        x2       x3       x4       x5        x6       x7  \
0  2.0  3.12372  -5.09810 -3.97276 -0.61368 -2.00124   7.05334  5.25202   
1  2.0  7.78090  -0.05704  4.41300  2.41022  0.25784   2.32726  2.83710   
2  2.0 -3.71252  -2.76142 -0.15100 -5.81984 -5.50412  -0.46390 -2.20914   
3  2.0 -3.17556  -4.15096  0.01476 -8.48308  1.83702 -11.23644  1.95670   
4  2.0  4.30104  10.52538 -2.53576 -5.36956 -2.30156  -0.72720  1.48468   

        x8       x9      x10  
0 -0.61902  2.64992 -4.52752  
1 -2.61094 -4.63708 -2.80790  
2 -2.23286 -4.70892 -2.86822  
3  0.12286  8.67520 -3.00258  
4  2.63052 -5.54058 -0.29714

In [19]:
totalsqrnorm = 0
print('start:', datetime.datetime.now())
for i in range(1000):
    seed = i
    if (seed % 100) == 0:
        print(seed)

    wpla = pla(data=temp, y=y)
    totalsqrnorm += np.linalg.norm(wpla) ** 2
print('end:', datetime.datetime.now())
avgsqrnorm = totalsqrnorm / 1000
print(avgsqrnorm)

start: 2021-10-17 11:49:17.363045
0
100
200
300
400
500
600
700
800
900
end: 2021-10-17 11:50:34.961602
1554.3914050656451


In [37]:
# Q16 unit vector
def get_unit_vector(z):
    unv = z / np.linalg.norm(z)
    return unv

In [41]:
temp = np.matrix(data_copy)
for i in range(len(temp)):
    temp[i] = get_unit_vector(temp[i])

temp

matrix([[ 0.15562923,  0.24307106, -0.39670668, ..., -0.0481688 ,
          0.2062025 , -0.35230722],
        [ 0.16929409,  0.65863018, -0.00482827, ..., -0.22100835,
         -0.39251511, -0.23768043],
        [ 0.17535853, -0.32551103, -0.24211928, ..., -0.19577553,
         -0.41287465, -0.25148342],
        ...,
        [ 0.12746078, -0.48619914,  0.11365295, ...,  0.05768747,
         -0.20033265,  0.0203899 ],
        [ 0.14123029, -0.2983857 , -0.27030206, ...,  0.38923067,
         -0.48757497, -0.18223791],
        [ 0.16428941, -0.41201649, -0.16916224, ..., -0.05177745,
          0.18761523,  0.10532101]])

In [42]:
temp = pd.DataFrame(temp, columns=x_cols)
temp.head(5)

x0        x1        x2        x3        x4        x5        x6  \
0  0.155629  0.243071 -0.396707 -0.309139 -0.047753 -0.155726  0.548853   
1  0.169294  0.658630 -0.004828  0.373547  0.204018  0.021825  0.196996   
2  0.175359 -0.325511 -0.242119 -0.013240 -0.510279 -0.482597 -0.040674   
3  0.111624 -0.177235 -0.231674  0.000824 -0.473459  0.102528 -0.627129   
4  0.136627  0.293820  0.719028 -0.173227 -0.366815 -0.157228 -0.049678   

         x7        x8        x9       x10  
0  0.408684 -0.048169  0.206203 -0.352307  
1  0.240152 -0.221008 -0.392515 -0.237680  
2 -0.193696 -0.195776 -0.412875 -0.251483  
3  0.109208  0.006857  0.484181 -0.167580  
4  0.101424  0.179701 -0.378498 -0.020299

In [43]:
totalsqrnorm = 0
print('start:', datetime.datetime.now())
for i in range(1000):
    seed = i
    if (seed % 100) == 0:
        print(seed)

    wpla = pla(data=temp, y=y)
    totalsqrnorm += np.linalg.norm(wpla) ** 2
print('end:', datetime.datetime.now())
avgsqrnorm = totalsqrnorm / 1000
print(avgsqrnorm)

start: 2021-10-17 11:56:59.926444
0
100
200
300
400
500
600
700
800
900
end: 2021-10-17 11:58:12.778230
7.136835806723664


In [47]:
# Q16
temp = data_copy.copy()
temp.drop('x0', axis=1, inplace=True)
x0_list = [0] * len(data)
temp = pd.concat([pd.Series(x0_list), temp], axis=1)
temp = temp.rename(columns={0: 'x0'})
temp.head(5)

x0       x1       x2       x3       x4       x5       x6       x7       x8  \
0   0  1.56186 -2.54905 -1.98638 -0.30684 -1.00062  3.52667  2.62601 -0.30951   
1   0  3.89045 -0.02852  2.20650  1.20511  0.12892  1.16363  1.41855 -1.30547   
2   0 -1.85626 -1.38071 -0.07550 -2.90992 -2.75206 -0.23195 -1.10457 -1.11643   
3   0 -1.58778 -2.07548  0.00738 -4.24154  0.91851 -5.61822  0.97835  0.06143   
4   0  2.15052  5.26269 -1.26788 -2.68478 -1.15078 -0.36360  0.74234  1.31526   

        x9      x10  
0  1.32496 -2.26376  
1 -2.31854 -1.40395  
2 -2.35446 -1.43411  
3  4.33760 -1.50129  
4 -2.77029 -0.14857

In [48]:
totalsqrnorm = 0
print('start:', datetime.datetime.now())
for i in range(1000):
    seed = i
    if (seed % 100) == 0:
        print(seed)

    wpla = pla(data=temp, y=y)
    totalsqrnorm += np.linalg.norm(wpla) ** 2
print('end:', datetime.datetime.now())
avgsqrnorm = totalsqrnorm / 1000
print(avgsqrnorm)

start: 2021-10-17 13:36:11.834823
0
100
200
300
400
500
600
700
800
900
end: 2021-10-17 13:38:46.400643
535.0082362209569
